services:
  store:
    image: batellerie
    build: ./
    # ports:
    #   - 0.0.0.0:12345:12345
    network_mode: host
    volumes:
      - ./data:/data/
    command: python -m batellerie.back store

  sync:
    image: batellerie
    build: ./
    volumes:
      - ./data:/data/
    command: python -m batellerie.back sync

  front:
    image: batellerie
    build: ./
    ports:
        - 8082:5000
    volumes:
      - ./data:/data/
    command: python -m batellerie.front
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: nginx-proxy
