services:
  store:
    image: batellerie
    build: ./
    # ports:
    #   - 0.0.0.0:12345:12345
    network_mode: host
    volumes:
      - ./data:/data/
    command: python -m batellerie.back store
    restart: unless-stopped

  sync:
    image: batellerie
    build: ./
    volumes:
      - ./data:/data/
    command: python -m batellerie.back sync
    restart: unless-stopped

  front:
    image: batellerie
    build: ./
    volumes:
      - ./data:/data/
    command: python -m batellerie.front
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.batellerie.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.batellerie.loadbalancer.server.port=5000"
      - "traefik.http.routers.batellerie.entrypoints=websecure"
      - "traefik.http.routers.batellerie.tls.certresolver=letsencrypt"
      - "traefik.http.routers.batellerie.tls=true"
