services:
  store:
    image: ais
    build: ./
    # ports:
    #   - 0.0.0.0:12345:12345
    network_mode: host
    volumes:
      - ./:/app/
    command: python back.py store

  sync:
    image: ais
    build: ./
    volumes:
      - ./:/app/
    command: python back.py sync

# networks:
#   default:
#     external:
#       name: nginx-proxy
